language: bash

env:
  global:
  - PATH=$PATH:/tmp/bin
  - TAG=2019042701

  matrix:
  #~ - ARCH=x86_64 BOOTSTRAP=x86_64
  #~ - ARCH=i686 BOOTSTRAP=i686
  - ARCH=x86_64-musl BOOTSTRAP=x86_64-musl

install:
- docker pull voidlinux/masterdir-$BOOTSTRAP:$TAG
- docker run -d --name void -v "$(pwd)":/hostrepo -v /tmp:/tmp -e PATH="$PATH" voidlinux/masterdir-$BOOTSTRAP:$TAG /bin/sh -c 'sleep inf'

before_script:
- echo before script
- travis/set_mirror.sh
#~ - common/travis/prepare.sh
#~ - common/travis/fetch_upstream.sh
#~ - common/travis/changed_templates.sh
#~ - common/travis/fetch-xtools.sh
#~ - common/travis/xlint.sh

script:
#~ - docker exec -t void hostrepo/common/travis/build.sh $BOOTSTRAP $ARCH; fi
- echo script

after_script:
#~ - docker exec -t void hostrepo/common/travis/show_files.sh $BOOTSTRAP $ARCH; fi
- echo after script

